---
- name: Logstash docker install and configuration
  connection: smart
  hosts: pipl
  remote_user: admin
  become: yes

  tasks:
    - name: build logstash configuration
      copy:
        src: "files/logstash/"
        dest: "/tmp/logstash"
        mode: '0777'

    - name: Start Logstash container
      docker_container:
        image: docker.elastic.co/logstash/logstash:6.3.2
        name: logstash
        hostname: logstash
        volumes:
        - /tmp/logstash:/usr/share/logstash/pipeline/  
        networks:
         - name: test_env
        restart_policy: always
        state: started

