---
- name: Nginx docker install and configuration
  connection: smart
  hosts: pipl
  remote_user: admin
  become: yes

  tasks:
    - name: create a configuration file
      copy:
        src: "files/nginx/"
        dest: "/tmp/nginx"
        mode: '0644'

    - name: start nginx docker
      docker_container:
         name: nginx
         image: nginx
         state: started
         expose:
         - 80:80
         ports:
         - "80:80"
         networks:
         - name: test_env
         volumes:
         - /tmp/nginx:/etc/nginx/conf.d/:ro